# Generated by Django 2.1 on 2018-08-26 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_user_sex'), ('app', '0003_auto_20180820_2216'), ('app', '0004_auto_20180820_2254'), ('app', '0005_auto_20180821_1756'), ('app', '0006_lesson_charge'), ('app', '0007_user_generation'), ('app', '0008_discount_pattern'), ('app', '0009_auto_20180826_1821'), ('app', '0010_auto_20180826_1821'), ('app', '0011_auto_20180826_1840'), ('app', '0012_auto_20180826_1846')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sex', models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basic_charge', models.IntegerField()),
                ('metered_charge', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='受講時間(h)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Curriculum', verbose_name='カリキュラム')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='ユーザー')),
                ('charge', models.IntegerField(null=True, verbose_name='料金')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='curriculums',
            field=models.ManyToManyField(through='app.Lesson', to='app.Curriculum', verbose_name='受講記録'),
        ),
        migrations.AddField(
            model_name='user',
            name='generation',
            field=models.IntegerField(null=True, verbose_name='年代'),
        ),
        migrations.CreateModel(
            name='Discount_pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_total_time', models.IntegerField(verbose_name='適用開始時間')),
                ('discount_per_hour', models.IntegerField(verbose_name='１時間あたりの割引額')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('curriculums', models.ManyToManyField(to='app.Curriculum', verbose_name='適用するカリキュラム')),
            ],
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=50, verbose_name='カリキュラム名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='basic_charge',
            field=models.IntegerField(verbose_name='基本料金'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='metered_charge',
            field=models.IntegerField(verbose_name='従量料金'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
