# Generated by Django 2.1 on 2018-08-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180820_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='carriculum',
            new_name='curriculum',
        ),
    ]
