# Generated by Django 2.1 on 2018-08-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180820_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lessons',
            new_name='curriculums',
        ),
    ]
