# Generated by Django 2.1 on 2018-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180821_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='charge',
            field=models.IntegerField(null=True),
        ),
    ]
