# Generated by Django 2.1 on 2018-08-25 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_total_time', models.IntegerField()),
                ('discount_per_hour', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('curriculums', models.ManyToManyField(to='app.Curriculum')),
            ],
        ),
    ]
