# Generated by Django 2.1 on 2018-08-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_curriculum_basic_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='basic_lesson_time',
            field=models.IntegerField(default=0, verbose_name='基本料金に含まれる時間'),
        ),
    ]
