# Generated by Django 2.1 on 2018-08-26 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180826_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='受講日'),
        ),
    ]
