# Generated by Django 2.1 on 2018-08-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_lesson_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.IntegerField(verbose_name='受講時間(h)'),
        ),
    ]
