# Generated by Django 2.1 on 2018-08-31 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180827_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='generation',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='受講時間(h)'),
        ),
    ]
