# Generated by Django 2.1 on 2018-08-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180831_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='charge',
        ),
    ]
